### ISSUE TITLE
bucket policy only - is it supported?

### ISSUE THREAD

**Issue by wmuizelaar** [GoogleCloudPlatform/berglas#59]
Hi,

I'm trying to get some things working with berglas, but in my organization policy it is stated that ACLs aren't allowed anymore, just IAM on buckets (see https://cloud.google.com/storage/docs/bucket-policy-only)

The documentation of berglas talks about IAM as well, but it seems like when I'm trying to give my own account (which is owner on the project) read permissions, it failes with the following error message:

```
$ berglas grant berglas-goingontheroad-nl/wordpress-db-user --member wietse@wietsemuizelaar.nl
failed to get Storage IAM policy: googleapi: Error 400: Object policies are disabled for bucket 'berglas-goingontheroad-nl' when Bucket Policy Only is enabled. Read more at https://cloud.google.com/storage/docs/bucket-policy-only., invalid
```

Is this a bug, or is it intentional that berglas requires per object ACLs?

Thanks,

Wietse

**Comment by sethvargo** [comment]
Hi @wmuizelaar 

Berglas relies on object-level IAM in buckets to grant access to secrets. If your organization prohibits object-level permissions, unfortunately you will not be able to use berglas. This is intentional, since you may have multiple secrets for an organization in a single bucket. You don't want to grant everyone access to all secrets, thus we rely on object-level permissions.
