### ISSUE TITLE
Berglas + Ruby GAE Flexible

### ISSUE THREAD

**Issue by veeral-patel** [GoogleCloudPlatform/berglas#94]
Hi - I'm running a Rails app on GAE Flexible - Ruby. I'd prefer not to write my own Dockerfile just so I can use Berglas. Is there any way to use Berglas with GAE Flexible - Ruby out of the box, without writing a Dockerfile?

**Comment by sethvargo** [comment]
Hi @veeral-patel 

That would require a Ruby library. I took a stab at [writing a Ruby library in a branch](https://github.com/GoogleCloudPlatform/berglas/tree/sethvargo/clients), but it wasn't pretty. We've since released [Secret Manager](https://cloud.google.com/secret-manager), which is a native service and will have a Ruby gem and samples published in the next few weeks.

**Comment by veeral-patel** [comment]
@sethvargo got it. Unfortunately I couldn't figure out how to manage secrets in GAE Ruby, which had prevented me from deploying my web app for a few days, so I switched over to Heroku and it's going great. Happy to re-consider GAE if I can get secrets working!
