### ISSUE TITLE
How to view permissions?

### ISSUE THREAD

**Issue by kevinsimper** [GoogleCloudPlatform/berglas#98]
What is the easiest way to see which permissions have been given with berglas?

**Comment by sethvargo** [comment]
Hey @kevinsimper - this is a difficult question to answer. You can see which permissions Berglas granted by looking at the IAM permissions to see who has permission to use the crypto key and access the storage object. However, there's no GCP API that queries permissions, only roles. Since organizations can make custom roles, as well as the top-level roles like owner/editor, it's actually not possible to definitively build a list of all things that have access to a secret. Does that make sense?

**Comment by kevinsimper** [comment]
@sethvargo Yeah that makes sense, but I was thinking a list must be able to fetch since you can both "grant" and "revoke".

Right now I have dug down and uses "gcloud kms keys get-iam-policy" and "gsutil iam get".

**Comment by sethvargo** [comment]
`revoke` is the direct opposite of `grant` (it "undoes" grant), meaning it removes the two IAM permissions that grant provides. If the entity has permissions at a higher level (such as project owner), it still retains access.
